name: RankSystem
version: 1.0.0
main: AcidPlugin\RankSystem\Main
api: [3.0.0, 3.1.0, 4.0.0]
author: AcidPlugin | §eFor issues report by §2Visiting GitHub.com/AcidPlugin

depend: [PureChat, PurePerms, EconomyAPI]
commands:
  rshop:
   description: "A rank shop system established for servers"
